import { describe, expect, it } from 'vitest'

describe('Clowder cat console', () => {
  it('routes the contact entry to a full cat management console', async () => {
    const router = await import('../src/router/index.ts?raw')
    const contactList = await import('../../../packages/contacts-vue/src/views/ContactList.vue?raw')
    const index = await import('../../../packages/contacts-vue/src/index.ts?raw')

    expect(index.default).toContain('ClowderCatConsolePage')
    expect(router.default).toContain('ClowderCatConsolePage')
    expect(router.default).toContain("path: 'clowder-cats'")
    expect(contactList.default).toContain('handleConfigureClowderCats')
    expect(contactList.default).toContain("router.push('/chat/clowder-cats')")
    expect(contactList.default).not.toContain('cat-action-buttons')
    expect(contactList.default).not.toContain('showCreateCatForm')
  })

  it('provides a robot-console style create/connect surface for cat contacts', async () => {
    const page = await import('../../../packages/contacts-vue/src/views/ClowderCatConsolePage.vue?raw')

    expect(page.default).toContain('猫猫设置')
    expect(page.default).toContain('Clowder 猫猫联系人')
    expect(page.default).toContain('createCatAndConnect')
    expect(page.default).toContain('deleteCatContact')
    expect(page.default).toContain('loadCatContactDirectory')
    expect(page.default).toContain('router.push(`/chat/conversation/${cat.directConversationId}/1`)')
    expect(page.default).toContain('form.alias')
    expect(page.default).toContain('form.clientId')
    expect(page.default).toContain('运行平台')
    expect(page.default).toContain('Codex')
    expect(page.default).toContain('Claude Code')
    expect(page.default).toContain('selectedProviderSkills')
    expect(page.default).toContain('clowderStore.catSkillCatalog[provider]')
    expect(page.default).toContain('skill-preview')
    expect(page.default).toContain('skill-row')
    expect(page.default).toContain('form.personality')
    expect(page.default).toContain('form.capabilitiesText')
    expect(page.default).toContain('const clientId = form.clientId')
    expect(page.default).toContain('clientId,')
    expect(page.default).toContain('form.authType')
    expect(page.default).toContain('添加方式')
    expect(page.default).toContain('API Key 账号')
    expect(page.default).toContain('OAuth 账号')
    expect(page.default).toContain('form.accountRef')
    expect(page.default).toContain('authType,')
    expect(page.default).toContain('accountRef: resolvedAccountRef.value')
    expect(page.default).toContain('selectedOAuthConfig')
    expect(page.default).toContain('loadLocalOAuthCapabilities')
    expect(page.default).toContain('console-layout')
    expect(page.default).toContain('cat-row')
    expect(page.default).not.toContain('connectExistingCat')
    expect(page.default).not.toContain('添加到联系人')
  })

  it('uses an AppDialog typed confirmation for deleting connected cats', async () => {
    const page = await import('../../../packages/contacts-vue/src/views/ClowderCatConsolePage.vue?raw')

    expect(page.default).toContain('AppDialog')
    expect(page.default).toContain('pendingDeleteCat')
    expect(page.default).toContain('deleteConfirmInput')
    expect(page.default).toContain('deleteConfirmMatches')
    expect(page.default).toContain('requestDeleteCat(cat)')
    expect(page.default).toContain('confirmDeleteCat')
    expect(page.default).toContain('clowderStore.deleteCatContact(cat.catId)')
    expect(page.default).toContain('confirm-text="删除"')
    expect(page.default).toContain('输入 ${pendingDeleteCat.displayName} 或 ${pendingDeleteCat.catId}')
    expect(page.default).not.toContain('window.confirm')
  })

  it('uses the full role template catalog for the create-cat dropdown', async () => {
    const page = await import('../../../packages/contacts-vue/src/views/ClowderCatConsolePage.vue?raw')

    expect(page.default).toContain('clowderStore.catRoleTemplates')
    expect(page.default).toContain('template.roleTemplateId')
    expect(page.default).toContain(':disabled="template.cloneable === false"')
    expect(page.default).not.toContain("cat.source === 'disconnected'")
  })

  it('shows platform model options and sends the selected model with create-cat requests', async () => {
    const page = await import('../../../packages/contacts-vue/src/views/ClowderCatConsolePage.vue?raw')

    expect(page.default).toContain('clowderStore.platformModelOptions')
    expect(page.default).toContain('recommendedModel')
    expect(page.default).toContain('applyRecommendedModel')
    expect(page.default).toContain('defaultOAuthAccountRef')
    expect(page.default).toContain("if (form.clientId === 'openai') return 'codex'")
    expect(page.default).toContain("if (form.clientId === 'anthropic') return 'claude'")
    expect(page.default).toContain('resolvedAccountRef')
    expect(page.default).toContain('v-if="!isOAuthAuth"')
    expect(page.default).toContain('v-for="model in modelOptions"')
    expect(page.default).toContain('model.default ?')
    expect(page.default).toContain("!isOAuthAuth.value ? { defaultModel: form.defaultModel.trim() || undefined } : {}")
    expect(page.default).toContain('form.clientId && !isOAuthAuth && modelOptions.length > 0')
    expect(page.default).toContain('form.clientId && !isOAuthAuth')
    expect(page.default).toContain('本机 OAuth')
    expect(page.default).toContain('clowderStore.loadLocalOAuthCapabilities()')
    expect(page.default).toContain('!oauthConfigMissing.value')
    expect(page.default).toContain('CLI 默认模型')
  })

  it('shows only existing connected cats in the contacts list', async () => {
    const page = await import('../../../packages/contacts-vue/src/views/ClowderCatConsolePage.vue?raw')

    expect(page.default).toContain('clowderStore.catContactDirectory.filter(cat => cat.connected)')
    expect(page.default).toContain('暂无猫猫联系人')
    expect(page.default).toContain('打开会话')
    expect(page.default).toContain('删除')
    expect(page.default).not.toContain('@click="connectCat(cat)"')
  })
})
